#!/usr/bin/env bash
# Install nginx on your web-01-server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
# As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
# You can’t use systemctl for restarting nginx

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
ufw allow nginx 80
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
nginx -t
service nginx start
