#!/usr/bin/env bash
# Script to configure Nginx to redirect /redirect_me to another page

# Create the redirection configuration
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Restart Nginx to apply changes
service nginx restart
