#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
Sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend eodenyire.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 12025-web-01 54.237.58.68:80
        server 12025-web-02 52.207.70.223:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
