#!/usr/bin/env bash
# Generates a compressed archive of a MySQL dump.

# Check if the correct number of arguments are provided
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <mysql_password>"
  exit 1
fi

# Create a MySQL dump of all databases and compress it in one step
mysqldump -uroot -p"$1" --all-databases | gzip > "$(date +%d-%m-%Y).tar.gz"
mysqldump -uroot --password="$11" --all-databases > backup.sql
