#!/usr/bin/env bash
# Script: 1-list_your_processes
# Description: Displays a list of currently running processes
# Requirements:
#   - Must show all processes, for all users, including those which might not have a TTY
#   - Display in a user-oriented format
#   - Show process hierarchy

#ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest

ps -auxf
