#!/usr/bin/env bash
# This script displays the PID and process name of processes whose name contain the word bash
pgrep bash | while read -r pid; do
    pname=$(ps -p "$pid" -o comm=)
    echo "$pid $pname"
done
