#!/usr/bin/env bash
# Configures Nginx to run as the 'nginx' user and listen on port 8080.
# Stops any running Apache service, adjusts Nginx configuration file permissions,
# updates the listening port, and starts Nginx as the 'nginx' user.
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start

