#!/usr/bin/env bash
# Configures Nginx to run as 'nginx' user and listen on port 8080, Stops Apache, updates Nginx file ownership and permissions
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
